### PR TITLE
Proposes a more efficient way for the time stepping

### PR DESCRIPTION
**Pull request by FrederikSchnack**
So far, the optimization is only for  the 4th order extrapolation scheme, until we are happy with the performance and extend it to the other brackets. The idea is:
- Pre-compute the rows and columns of the bracket entries of the RHS matrix `J_phi`and pre-allocate `J_phi` when creating the class `PoloidalAdvectionArakawa`
- Use a pyccelized routine to compute the data vector from given `phi` in every time step
- Update the `J_phi` in place from the data, row and column vectors 
The second point is currently only implemented in python, but @dominikbell wanted to take care of it

### CODE REVIEW

**Comment by dominikbell** [comment]
As we discussed, `pyccel` cannot handle `scipy.sparse` matrices so the second function you marked as "to be pyccelized" will not be able to pyycelize.

As I implemented it now, only the `data_assembly` function is pyccelised but the data assignment into the sparse matrix is still python speed. I wonder if it would be faster to create a new `scipy.sparse` matrix in that function instead of updating the entries of the old matrix.

**Comment by FrederikSchnack** [comment]
> As we discussed, `pyccel` cannot handle `scipy.sparse` matrices so the second function you marked as "to be pyccelized" will not be able to pyycelize.
 I know, I was only talking about the first function. Maybe the comment was not clear.

> As I implemented it now, only the `data_assembly` function is pyccelised but the data assignment into the sparse matrix is still python speed. I wonder if it would be faster to create a new `scipy.sparse` matrix in that function instead of updating the entries of the old matrix.
> 
> EDIT: I tested it, the reassignment as it is implemented now is faster (about a factor of 2), so I suggest we keep the code as it is now. We could also pyccelize for the first creation of the matrix, but this would give only a small speed boost overall.
Thanks! I don't see why it should be faster to create a new matrix every time.

**Comment by FrederikSchnack** [comment]
Seems like I was too fast and also implemented the usage of the new routines in the advection step, but my version is more or less the same then yours :+1: 
By doing these changes, the bottleneck becomes the linear solve in the time-stepping. The assembly of the RHS is now very fast and dominated by other pygyro function calls.

**Review by dominikbell — APPROVED** [review]
lgtm

**Pull request merged**
