### PR TITLE
Add second order Arakawa scheme to PyGyro, draft for fourth order

### PR DESCRIPTION
**Pull request by FrederikSchnack**
With periodic and Dirichlet boundary conditions. Care that PyGyro orders variables differently than our current experiment code!

### CODE REVIEW

**Comment by FrederikSchnack** [comment]
The visual test should be running properly out of the box, although with some numerical noise. (Because of the lower order and not a lot of points?)

**Comment by dominikbell** [comment]
Is it on purpose that in the boundary terms the `i1` is set and then also used as a loop variable while `i0` is not assigned? Your code uses then the last value stored in `i0` from the previous loop.

**Comment by FrederikSchnack** [comment]
> Is it on purpose that in the boundary terms the `i1` is set and then also used as a loop variable while `i0` is not assigned? Your code uses then the last value stored in `i0` from the previous loop.
> 
> I'm referring to [these lines](https://github.com/pyccel/pygyro/blob/pygyro_adap_akw/pygyro/arakawa/discrete_brackets_polar.py#L310-#L312) and [these lines](https://github.com/pyccel/pygyro/blob/pygyro_adap_akw/pygyro/arakawa/discrete_brackets_polar.py#L371-#L373)

Well spotted! That is indeed an artifact from rearranging the variables and should be fixed now.

**Comment by dominikbell** [comment]
Also, the diffusive behaviour one can observe after some time should be investigated further.

[This image](https://ibb.co/2jy8vnW) was generated using your bracket and the `test_poloidalAdvectionArakawa_constantAdv` code for `T=600`, `dt = 0.01` and a mesh of size `[30, 20]`.

**Comment by FrederikSchnack** [comment]
> Also, the diffusive behaviour one can observe after some time should be investigated further.
> 
> [This image](https://ibb.co/2jy8vnW) was generated using your bracket and the `test_poloidalAdvectionArakawa_constantAdv` code for `T=600`, `dt = 0.01` and a mesh of size `[30, 20]`.
> 
> EDIT: this was done before the change of variable names. [The same result now](https://ibb.co/zVrGt7H) doesn't look much better.

I am unable to access (the domain of) your images. But [30, 20] does not seem like a lot of points for a scheme of order 2, but I agree. It would be good if someone could check that "my" bracket is the same as in Arakawas paper, which I believe since I didn't spot any typos. If its fine, we can try to trace the source of the problem in our advection step.

**Comment by dominikbell** [comment]
Regarding [this problem](https://github.com/pyccel/pygyro/blob/pygyro_adap_akw/pygyro/advection/advection.py#L688-#L693) we can use
```
ind_all = np.arange(N_points)
ind_bd = ind_all[np.where((ind_all % self._nPoints_r == 0) | (ind_all % self._nPoints_r == self._nPoints_r - 1 ))]
```
which is also significantly faster than the way you did it (never use `for`-loops in python ;) )

**Comment by FrederikSchnack** [comment]
> Regarding [this problem](https://github.com/pyccel/pygyro/blob/pygyro_adap_akw/pygyro/advection/advection.py#L688-#L693) we can use
> 
> ```
> ind_all = np.arange(N_points)
> ind_bd = ind_all[np.where((ind_all % self._nPoints_r == 0) | (ind_all % self._nPoints_r == self._nPoints_r - 1 ))]
> ```
> 
> which is also significantly faster than the way you did it (never use long `for`-loops in python ;) )

Considering the size of the parameters _significantly_ might be a stretch, at least by the benchmark I did. But I agree, let's make it a bit more transparent tho and put it in the construction of the class as we only need to do it once. (see latest commit)

**Comment by FrederikSchnack** [comment]
This pull request is getting pretty crowded and contains more than the title suggests. I think we should merge the original content (up until two commits ago) and create new branches for fixed testing of the bracket and maybe a new structure of utilities (if needed). I would prefer to do _purely_ cosmetic changes of the code only right before merging, especially when still working on it, mainly because I'm selfish and don't want to locally merge everything in my current work-in-progress code.

**Comment by dominikbell** [comment]
I think we can merge it, it passes the tests and so we have something to show tomorrow that Virginie can also test herself.

**Comment by FrederikSchnack** [comment]
Your first commit is still **breaking** the periodic bracket since you changed the variables to the same name, as written in the review above. I think it would be better to properly discuss how and what to test . For the presentation, we can also show code from a not merged branch.

**Comment by FrederikSchnack** [comment]
As discussed, this branch contains the Arakawa bracket of order 2 and 4, with Dirichlet and periodic boundary conditions. The implementation of the Dirichlet BC is one-to-one the version from Arakawas paper for order 2 and a canonical continuation of this idea for order 4. The discrete brackets solve algebraically the conservation properties (for random vectors `f` and `phi` that are constant in the `r` boundary), i.e.
```
$julia algebraic_conservation.jl
periodic order 2:
norm(Jp_2 + Jp_2') = 9.301533857380602e-13
sum(Jp_2 * f) = 7.389644451905042e-12
f' * Jp_2 * f = 1.432454155292362e-11
phi' * Jp_2 * f = 2.6989750648006164e-11
dirichlet order 2:
norm(Jd_2 + Jd_2') = 8.707253296212876e-13
sum(Jd_2 * f) = 3.410605131648481e-13
f' * Jd_2 * f = -9.094947017729282e-13
phi' * Jd_2 * f = -1.4220270183799595e-12
periodic order 4:
norm(Jp_4 + Jp_4') = 1.8603067714761205e-12
sum(Jp_4 * f) = 1.6370904631912708e-11
f' * Jp_4 * f = 2.9331204132176936e-11
phi' * Jp_4 * f = 3.875056920503094e-11
dirichlet order 4:
norm(Jd_4 + Jd_4') = 1.7414506592425753e-12
sum(Jd_4 * f) = -4.547473508864641e-13
f' * Jd_4 * f = -2.2737367544323206e-12
phi' * Jd_4 * f = 6.645272181031161e-12
```

Of course, this needs some more testing, e.g. exact order benchmarks, but my local examples looked good!

**Review by dominikbell — APPROVED** [review]
lgtm

**Pull request merged**
